package br.com.ticpass.pos.queue.error

import br.com.ticpass.pos.R

/**
 * Maps ProcessingErrorEvent types to string resource keys
 * This centralized mapping makes it easy to maintain error message mappings
 */
object ProcessingErrorEventResourceMapper {
    
    /**
     * Get the string resource key for a ProcessingErrorEvent
     * @param error The ProcessingErrorEvent to map
     * @return The string resource key corresponding to the error
     */
    fun getErrorResourceKey(error: ProcessingErrorEvent): Int {
        return when (error) {
            is ProcessingErrorEvent.REMOVE_CARD_BEFORE_PROCEEDING -> R.string.error_remove_card_before_proceeding
            is ProcessingErrorEvent.CARD_REACH_NOT_ALLOWED -> R.string.error_card_reach_not_allowed
            is ProcessingErrorEvent.PROCESSOR_NOT_FOUND -> R.string.error_processor_not_found
            is ProcessingErrorEvent.INVALID_TRANSACTION_BUFFER -> R.string.error_invalid_transaction_buffer
            is ProcessingErrorEvent.INVALID_CARD_USE_ANOTHER -> R.string.error_invalid_card_use_another
            is ProcessingErrorEvent.ACQUIRER_SERVER_ERROR -> R.string.error_acquirer_server_error
            is ProcessingErrorEvent.CARD_BRAND_NOT_ACCEPTED -> R.string.error_card_brand_not_accepted
            is ProcessingErrorEvent.DATA_PACKET_FORMAT -> R.string.error_data_packet_format
            is ProcessingErrorEvent.TRANSACTION_INVALID_AMOUNT -> R.string.error_transaction_invalid_amount
            is ProcessingErrorEvent.TRANSACTION_CODE_TOO_LONG -> R.string.error_transaction_code_too_long
            is ProcessingErrorEvent.INVALID_TRANSACTION_AMOUNT_FORMAT -> R.string.error_invalid_transaction_amount_format
            is ProcessingErrorEvent.TRANSACTION_NULL_AMOUNT -> R.string.error_transaction_null_amount
            is ProcessingErrorEvent.TRANSACTION_NULL_SALE_CODE -> R.string.error_transaction_null_sale_code
            is ProcessingErrorEvent.INTERNATIONAL_CARD_NOT_ALLOWED -> R.string.error_international_card_not_allowed
            is ProcessingErrorEvent.UPDATE_APP -> R.string.error_update_app
            is ProcessingErrorEvent.ERROR_REVERSING_TRANSACTION -> R.string.error_reversing_transaction
            is ProcessingErrorEvent.INVALID_TRANSACTION_PERFORM_CASH -> R.string.error_invalid_transaction_perform_cash
            is ProcessingErrorEvent.ERROR_CONFIRMING_TRANSACTION -> R.string.error_confirming_transaction
            is ProcessingErrorEvent.RESPONSE_TLV_SIZE -> R.string.error_response_tlv_size
            is ProcessingErrorEvent.INVALID_PIX_KEY -> R.string.error_invalid_pix_key
            is ProcessingErrorEvent.INVALID_FILE -> R.string.error_invalid_file
            is ProcessingErrorEvent.ATTEMPTS_EXCEEDED -> R.string.error_attempts_exceeded
            is ProcessingErrorEvent.INSTALLMENT_NOT_ALLOWED -> R.string.error_installment_not_allowed
            is ProcessingErrorEvent.OPERATION_NOT_PERFORMED -> R.string.error_operation_not_performed
            is ProcessingErrorEvent.USE_CREDIT_FOR_PREAUTH -> R.string.error_use_credit_for_preauth
            is ProcessingErrorEvent.CAPTURE_AMOUNT_EXCEEDED -> R.string.error_capture_amount_exceeded
            is ProcessingErrorEvent.BRAND_NOT_ALLOWED_PREAUTH -> R.string.error_brand_not_allowed_preauth
            is ProcessingErrorEvent.PREAUTH_EXPIRED -> R.string.error_preauth_expired
            is ProcessingErrorEvent.PREAUTH_NOT_ENABLED -> R.string.error_preauth_not_enabled
            is ProcessingErrorEvent.AMOUNT_TOO_LOW -> R.string.error_amount_too_low
            is ProcessingErrorEvent.PREAUTH_QUANTITY_EXCEEDED -> R.string.error_preauth_quantity_exceeded
            is ProcessingErrorEvent.REQUEST_IN_PROGRESS -> R.string.error_request_in_progress
            is ProcessingErrorEvent.UPDATE_DEVICE -> R.string.error_update_device
            is ProcessingErrorEvent.TRANSACTION_CANNOT_BE_REVERSED -> R.string.error_transaction_cannot_be_reversed
            is ProcessingErrorEvent.TRANSACTION_ALREADY_REVERSED -> R.string.error_transaction_already_reversed
            is ProcessingErrorEvent.TRANSACTION_NOT_AUTHORIZED_CONTACT_MANAGER -> R.string.error_transaction_not_authorized_contact_manager
            is ProcessingErrorEvent.CARD_ERROR_POORLY_INSERTED -> R.string.error_card_error_poorly_inserted
            is ProcessingErrorEvent.INVALID_INPUT_MODE -> R.string.error_invalid_input_mode
            is ProcessingErrorEvent.READER_WITHOUT_KEY -> R.string.error_reader_without_key
            is ProcessingErrorEvent.FILE_OPERATION_FAILURE -> R.string.error_file_operation_failure
            is ProcessingErrorEvent.CONTACTLESS_NOT_AUTHORIZED -> R.string.error_contactless_not_authorized
            is ProcessingErrorEvent.INVALID_SELECTED_OPTION -> R.string.error_invalid_selected_option
            is ProcessingErrorEvent.CARD_INVALIDATED -> R.string.error_card_invalidated
            is ProcessingErrorEvent.BLOCKED_CARD -> R.string.error_blocked_card
            is ProcessingErrorEvent.EXPIRED_CARD -> R.string.error_expired_card
            is ProcessingErrorEvent.INTERNAL_PINPAD_ERROR -> R.string.error_internal_pinpad_error
            is ProcessingErrorEvent.MAX_TIME_EXCEEDED -> R.string.error_max_time_exceeded
            is ProcessingErrorEvent.PINPAD_ERROR -> R.string.error_pinpad_error
            is ProcessingErrorEvent.RESPONSE_TIME_EXCEEDED -> R.string.error_response_time_exceeded
            is ProcessingErrorEvent.COULD_NOT_LOCATE_REFERENCE_DUPLICATED -> R.string.error_could_not_locate_reference_duplicated
            is ProcessingErrorEvent.READ_ERROR -> R.string.error_read_error
            is ProcessingErrorEvent.PRINTER_MALFUNCTION -> R.string.error_printer_malfunction
            is ProcessingErrorEvent.MESSAGE_BUFFER_OVERFLOW -> R.string.error_message_buffer_overflow
            is ProcessingErrorEvent.NULL_TRANSACTION_RESULT -> R.string.error_null_transaction_result
            is ProcessingErrorEvent.TOKEN_NOT_FOUND -> R.string.error_token_not_found
            is ProcessingErrorEvent.ROOT_PERMISSION_DETECTED -> R.string.error_root_permission_detected
            is ProcessingErrorEvent.NO_AUTHENTICATION_DATA -> R.string.error_no_authentication_data
            is ProcessingErrorEvent.IMAGE_PROCESSING_FAILED -> R.string.error_image_processing_failed
            is ProcessingErrorEvent.SDK_PRINT_UNAVAILABLE -> R.string.error_sdk_print_unavailable
            is ProcessingErrorEvent.DATA_PACKAGE_TOO_LONG -> R.string.error_data_package_too_long
            is ProcessingErrorEvent.FONT_LIBRARY_NOT_INSTALLED -> R.string.error_font_library_not_installed
            is ProcessingErrorEvent.PRINTING_UNFINISHED -> R.string.error_printing_unfinished
            is ProcessingErrorEvent.CARD_READER_NOT_INITIALIZED -> R.string.error_card_reader_not_initialized
            is ProcessingErrorEvent.INVALID_DEVICE_ID -> R.string.error_invalid_device_id
            is ProcessingErrorEvent.MISSING_INSTALLMENT_COEFFICIENTS -> R.string.error_missing_installment_coefficients
            is ProcessingErrorEvent.AUTHENTICATION_ERROR -> R.string.error_authentication_error
            is ProcessingErrorEvent.NO_LAST_TRANSACTION_DATA -> R.string.error_no_last_transaction_data
            is ProcessingErrorEvent.APPLICATION_NAME_REQUIRED -> R.string.error_application_name_required
            is ProcessingErrorEvent.APPLICATION_NAME_TOO_LONG -> R.string.error_application_name_too_long
            is ProcessingErrorEvent.APPLICATION_VERSION_TOO_LONG -> R.string.error_application_version_too_long
            is ProcessingErrorEvent.CORRUPTED_RECEPTION_BUFFER -> R.string.error_corrupted_reception_buffer
            is ProcessingErrorEvent.CONNECTION_DRIVER_ERROR -> R.string.error_connection_driver_error
            is ProcessingErrorEvent.CONNECTION_DRIVER_NOT_FOUND -> R.string.error_connection_driver_not_found
            is ProcessingErrorEvent.CONNECTION_ERROR_SIM_WIFI -> R.string.error_connection_error_sim_wifi
            is ProcessingErrorEvent.WIFI_CONNECTION_ERROR -> R.string.error_wifi_connection_error
            is ProcessingErrorEvent.CONNECTION_ERROR_NO_INTERNET -> R.string.error_connection_error_no_internet
            is ProcessingErrorEvent.CONNECTION_ERROR -> R.string.error_connection_error
            is ProcessingErrorEvent.NOT_CONNECTED_TO_WIFI -> R.string.error_not_connected_to_wifi
            is ProcessingErrorEvent.OPERATION_NOT_AUTHORIZED -> R.string.error_operation_not_authorized
            is ProcessingErrorEvent.PPP_AUTH_FAILURE -> R.string.error_ppp_auth_failure
            is ProcessingErrorEvent.NO_NETWORK_SIGNAL -> R.string.error_no_network_signal
            is ProcessingErrorEvent.NETWORK_OPERATOR_TIMEOUT -> R.string.error_network_operator_timeout
            is ProcessingErrorEvent.SIM_CARD_NOT_RESPONDING -> R.string.error_sim_card_not_responding
            is ProcessingErrorEvent.NETWORK_OPERATOR_UNAVAILABLE -> R.string.error_network_operator_unavailable
            is ProcessingErrorEvent.CARD_OPERATION_FAILED -> R.string.error_card_operation_failed
            is ProcessingErrorEvent.DEVICE_DEACTIVATED -> R.string.error_device_deactivated
            is ProcessingErrorEvent.TABLE_LOADING_ERROR -> R.string.error_table_loading_error
            is ProcessingErrorEvent.COULD_NOT_CONFIGURE_INSTALLMENT -> R.string.error_could_not_configure_installment
            is ProcessingErrorEvent.PLEASE_LOGIN_AGAIN -> R.string.error_please_login_again
            is ProcessingErrorEvent.TRY_AGAIN -> R.string.error_try_again
            is ProcessingErrorEvent.MAX_DATE_FOR_REVERSAL_EXCEEDED -> R.string.error_max_date_for_reversal_exceeded
            is ProcessingErrorEvent.ONLY_LETTERS_AND_NUMBERS -> R.string.error_only_letters_and_numbers
            is ProcessingErrorEvent.COULD_NOT_IDENTIFY_CARD -> R.string.error_could_not_identify_card
            is ProcessingErrorEvent.ONLY_TOTAL_REVERSAL_ALLOWED -> R.string.error_only_total_reversal_allowed
            is ProcessingErrorEvent.OPERATION_NOT_PERFORMED_ENTER_PASSWORD -> R.string.error_operation_not_performed_enter_password
            is ProcessingErrorEvent.USE_CHIP_INVALID_PAYMENT -> R.string.error_invalid_card_use_chip
            is ProcessingErrorEvent.UNEXPECTED_ERROR -> R.string.error_unexpected
            is ProcessingErrorEvent.OPERATION_TIME_EXCEEDED -> R.string.error_operation_time_exceeded
            is ProcessingErrorEvent.CONNECTION_REFUSED -> R.string.error_connection_refused
            is ProcessingErrorEvent.TRANSACTION_NOT_FOUND -> R.string.error_transaction_not_found
            is ProcessingErrorEvent.INVALID_ENTRY_MODE -> R.string.error_invalid_entry_mode
            is ProcessingErrorEvent.TRANSACTION_ALREADY_REFUNDED -> R.string.error_transaction_already_refunded
            is ProcessingErrorEvent.TLV_RESPONSE_TOO_LARGE -> R.string.error_tlv_response_too_large
            is ProcessingErrorEvent.INVALID_PAYMENT_METHOD -> R.string.error_invalid_mode
            is ProcessingErrorEvent.DUPLICATE_TRANSACTION -> R.string.error_duplicate_transaction
            is ProcessingErrorEvent.PASSWORD_REQUIRED -> R.string.error_password_required
            is ProcessingErrorEvent.CHIP_REQUIRED -> R.string.error_chip_required
            is ProcessingErrorEvent.USE_CHIP_FOR_TRANSACTION -> R.string.error_chip_required
            is ProcessingErrorEvent.ERROR_OPENING_CRYPTOGRAM -> R.string.error_cryptogram_error
            is ProcessingErrorEvent.TRANSACTION_CONFIRMATION_ERROR -> R.string.error_transaction_confirmation_error
            is ProcessingErrorEvent.TERMINAL_NOT_FOUND -> R.string.error_terminal_not_found
            is ProcessingErrorEvent.PRODUCT_NOT_ENABLED -> R.string.error_product_not_enabled
            is ProcessingErrorEvent.INVALID_POS_KEY -> R.string.error_invalid_pos_key
            is ProcessingErrorEvent.INVALID_TRANSACTION -> R.string.error_invalid_transaction
            is ProcessingErrorEvent.OPERATION_NOT_AUTHORIZED_BY_HOST -> R.string.error_transaction_denied_by_host
            is ProcessingErrorEvent.INVALID_CARD -> R.string.error_invalid_card
            is ProcessingErrorEvent.OPERATION_REJECTED_BY_CARD -> R.string.error_operation_rejected_by_card
            is ProcessingErrorEvent.TELECOM_PROVIDER_UNAVAILABLE -> R.string.error_telecom_provider_unavailable
            is ProcessingErrorEvent.HOST_RESPONSE_TIMEOUT -> R.string.error_host_response_timeout
            is ProcessingErrorEvent.TRY_AGAIN_LATER -> R.string.error_try_again_later
            is ProcessingErrorEvent.TRANSACTION_FAILURE -> R.string.error_transaction_failure
            is ProcessingErrorEvent.SIM_CARD_ERROR -> R.string.error_sim_card_error
            is ProcessingErrorEvent.SIM_CARD_MISSING -> R.string.error_sim_card_missing
            is ProcessingErrorEvent.NO_GSM_SIGNAL -> R.string.error_no_gsm_signal
            is ProcessingErrorEvent.NETWORK_ATTACHMENT_ERROR -> R.string.error_network_attachment_error
            is ProcessingErrorEvent.GPRS_CONNECTION_ERROR -> R.string.error_gprs_connection_error
            is ProcessingErrorEvent.SOCKET_CONNECTION_ERROR -> R.string.error_socket_connection_error
            is ProcessingErrorEvent.PRINTER_OUT_OF_PAPER -> R.string.error_printer_out_of_paper
            is ProcessingErrorEvent.PRINTER_OVERVOLTAGE -> R.string.error_printer_overvoltage
            is ProcessingErrorEvent.PRINTER_OVERHEATING -> R.string.error_printer_overheating
            is ProcessingErrorEvent.MODEM_INITIALIZATION_PENDING -> R.string.error_modem_initialization_pending
            is ProcessingErrorEvent.ACQUIRER_SERVER_CONNECTION_ERROR -> R.string.error_server_connection_error
            is ProcessingErrorEvent.TERMINAL_NOT_CONFIGURED -> R.string.error_terminal_not_configured
            is ProcessingErrorEvent.INVALID_PARAMETER -> R.string.error_invalid_parameter
            is ProcessingErrorEvent.INITIALIZATION_ERROR -> R.string.error_initialization_error
            is ProcessingErrorEvent.TRANSACTION_NOT_AUTHORIZED_BY_SERVER -> R.string.error_transaction_denied_by_server
            is ProcessingErrorEvent.COMMUNICATION_TIMEOUT -> R.string.error_communication_timeout
            is ProcessingErrorEvent.WIFI_NETWORKS_NOT_FOUND -> R.string.error_wifi_networks_not_found
            is ProcessingErrorEvent.LOW_BATTERY -> R.string.error_low_battery
            is ProcessingErrorEvent.PRINTER_BUSY -> R.string.error_printer_busy
            is ProcessingErrorEvent.PRINT_DATA_FORMAT_ERROR -> R.string.error_invalid_print_format
            is ProcessingErrorEvent.PRINTER_ERROR -> R.string.error_printer_error
            is ProcessingErrorEvent.TRANSACTION_CONFIRMATION_IN_PROGRESS -> R.string.error_transaction_confirmation_in_progress
            is ProcessingErrorEvent.PRINT_FILE_NOT_FOUND -> R.string.error_print_file_not_found
            is ProcessingErrorEvent.MOBILE_COMMUNICATION_ERROR -> R.string.error_mobile_communication_error
            is ProcessingErrorEvent.REQUEST_CANNOT_BE_COMPLETED -> R.string.error_request_cannot_be_completed
            is ProcessingErrorEvent.REQUEST_CANNOT_BE_EXECUTED -> R.string.error_request_cannot_be_executed
            is ProcessingErrorEvent.MINIMUM_INSTALLMENT_AMOUNT -> R.string.error_invalid_installment_value
            is ProcessingErrorEvent.INVALID_INSTALLMENT_METHOD -> R.string.error_invalid_installment_type
            is ProcessingErrorEvent.REFUND_ERROR -> R.string.error_refund_error
            is ProcessingErrorEvent.INVALID_CARD_NUMBER -> R.string.error_invalid_card_number
            is ProcessingErrorEvent.TRANSACTION_NOT_AUTHORIZED_BY_ISSUER -> R.string.error_transaction_not_authorized_by_issuer
            is ProcessingErrorEvent.INVALID_CARD_DATA -> R.string.error_invalid_card_data
            is ProcessingErrorEvent.ACCOUNT_CLOSED -> R.string.error_account_closed
            is ProcessingErrorEvent.CHECK_PASSWORD -> R.string.error_incorrect_password
            is ProcessingErrorEvent.TRANSACTION_CANNOT_BE_CONFIRMED -> R.string.error_transaction_cannot_be_confirmed
            is ProcessingErrorEvent.TRANSACTION_CANNOT_BE_CANCELLED -> R.string.error_transaction_cannot_be_cancelled
            is ProcessingErrorEvent.TRANSACTION_NOT_AUTHORIZED_BY_ACQUIRER -> R.string.error_transaction_not_authorized_by_acquirer
            is ProcessingErrorEvent.SELLER_BLOCKED -> R.string.error_seller_blocked
            is ProcessingErrorEvent.EMAIL_NOT_CONFIRMED -> R.string.error_email_not_confirmed
            is ProcessingErrorEvent.INVALID_READER_OR_ACTIVATION_CODE -> R.string.error_invalid_reader_or_activation_code
            is ProcessingErrorEvent.INVALID_BIN -> R.string.error_invalid_bin
            is ProcessingErrorEvent.INVALID_HOLDER -> R.string.error_invalid_holder
            is ProcessingErrorEvent.INACTIVE_READER -> R.string.error_inactive_reader
            is ProcessingErrorEvent.INVALID_CARD_NOT_ACCEPTED -> R.string.error_card_brand_not_accepted
            is ProcessingErrorEvent.INSTALLMENT_NOT_ALLOWED_PREPAID -> R.string.error_installment_not_allowed
            is ProcessingErrorEvent.OPERATION_TIMEOUT -> R.string.error_communication_timeout
            is ProcessingErrorEvent.TERMINAL_COMMUNICATION_ERROR -> R.string.error_communication_interrupted
            is ProcessingErrorEvent.INVALID_APPLICATION_PARAMETER -> R.string.error_invalid_parameter
            is ProcessingErrorEvent.MAC_GENERATION_FAIL -> R.string.error_failed_to_generate_mac
            is ProcessingErrorEvent.ONLY_TOTAL_REFUND_ALLOWED -> R.string.error_only_total_refund_allowed
            is ProcessingErrorEvent.ERROR_RESPONSE_MESSAGE_VALIDATION -> R.string.error_error_response_message_validation
            is ProcessingErrorEvent.CASH_ONLY_TRANSACTION -> R.string.error_invalid_transaction_perform_cash
            is ProcessingErrorEvent.TRANSACTION_NOT_AUTHORIZED -> R.string.error_not_authorized
            is ProcessingErrorEvent.FEATURE_UNAVAILABLE -> R.string.error_feature_unavailable
            is ProcessingErrorEvent.OPERATION_CANCELLED -> R.string.error_operation_cancelled_retry
            is ProcessingErrorEvent.DEVICE_NOT_ACTIVATED -> R.string.error_device_deactivated
            is ProcessingErrorEvent.NO_MESSAGE -> R.string.error_no_message
            is ProcessingErrorEvent.WIFI_NETWORK_UNAVAILABLE -> R.string.error_wifi_network_unavailable
            is ProcessingErrorEvent.WIFI_NOT_CONNECTED -> R.string.error_not_connected_to_wifi
            is ProcessingErrorEvent.WIFI_AUTH_ERROR -> R.string.error_wifi_auth_error
            is ProcessingErrorEvent.INTERNET_CONNECTION_ERROR -> R.string.error_connection_error_no_internet
            is ProcessingErrorEvent.INVALID_MENU_OPTION -> R.string.error_invalid_selected_option
            is ProcessingErrorEvent.COMMUNICATION_ERROR -> R.string.error_communication_interrupted
            is ProcessingErrorEvent.CANCELLED_BY_USER -> R.string.error_operation_canceled_by_user
            is ProcessingErrorEvent.PRINT_ERROR_LOW_BATTERY -> R.string.error_low_battery
            is ProcessingErrorEvent.INVALID_INSTALLMENTS_COUNT -> R.string.error_invalid_count_for_installment
            is ProcessingErrorEvent.INVALID_INSTALLMENT_AMOUNT -> R.string.error_minimum_installment_amount
            is ProcessingErrorEvent.INVALID_TRANSACTION_AMOUNT -> R.string.error_transaction_invalid_amount
            is ProcessingErrorEvent.CARD_NOT_IDENTIFIED -> R.string.error_could_not_identify_card
            is ProcessingErrorEvent.MAX_CHARACTERS -> R.string.error_max_10_characters
            is ProcessingErrorEvent.INVALID_CHARACTERS -> R.string.error_max_10_characters
            is ProcessingErrorEvent.APP_UPDATE -> R.string.error_update_app
            is ProcessingErrorEvent.OPERATION_NOT_COMPLETED -> R.string.error_operation_failure
            is ProcessingErrorEvent.TERMINAL_UPDATE_REQUIRED -> R.string.error_update_device
            is ProcessingErrorEvent.REFUND_TIME_LIMIT_EXCEEDED -> R.string.refund_time_limit_exceeded
            is ProcessingErrorEvent.TRANSACTION_CANNOT_BE_REFUNDED -> R.string.error_refund_error
            is ProcessingErrorEvent.INTERNATIONAL_CARD_NOT_SUPPORTED -> R.string.error_international_card_not_supported
            is ProcessingErrorEvent.AUTHENTICATION_REQUIRED -> R.string.error_please_login_again
            is ProcessingErrorEvent.INSTALLMENT_CONFIGURATION_ERROR -> R.string.error_could_not_configure_installment
            is ProcessingErrorEvent.DUPLICATE_REFERENCE -> R.string.error_could_not_locate_reference_duplicated
            is ProcessingErrorEvent.INVALID_READER_SERIAL_NUMBER -> R.string.error_invalid_embedded_reader_serial
            is ProcessingErrorEvent.UNIDENTIFIED_READER_SERIAL_NUMBER -> R.string.error_reader_serial_not_identified
            is ProcessingErrorEvent.INCORRECT_ACTIVATION_CODE -> R.string.error_invalid_reader_or_activation_code
            
            // New ProcessingErrorEvent objects added for Stone error mapping
            is ProcessingErrorEvent.CARD_READ_ERROR -> R.string.error_read_error
            is ProcessingErrorEvent.CARD_READ_CANCELED -> R.string.error_operation_canceled_by_user
            is ProcessingErrorEvent.CARD_READ_MULTI_ERROR -> R.string.error_card_read_multi_error
            is ProcessingErrorEvent.CARD_HOLDER_READ_ERROR -> R.string.error_card_holder_read_error
            is ProcessingErrorEvent.PINPAD_CONNECTION_NOT_FOUND -> R.string.error_connection_error_no_internet
            is ProcessingErrorEvent.PINPAD_ALREADY_CONNECTED -> R.string.error_pinpad_already_connected
            is ProcessingErrorEvent.PINPAD_CLOSED_CONNECTION -> R.string.error_communication_interrupted
            is ProcessingErrorEvent.IO_ERROR_WITH_PINPAD -> R.string.error_pinpad_error
            is ProcessingErrorEvent.TRANSACTION_APP_BLOCKED -> R.string.error_blocked_card
            is ProcessingErrorEvent.CVV_NOT_PROVIDED -> R.string.error_cvv_not_provided
            is ProcessingErrorEvent.CVV_INVALID -> R.string.error_invalid_card_data
            is ProcessingErrorEvent.NO_TRANSACTION_TYPE -> R.string.error_no_transaction_type
            is ProcessingErrorEvent.WRONG_TRANSACTION_TYPE -> R.string.error_invalid_transaction_generic
            is ProcessingErrorEvent.INVALID_APPLICATION -> R.string.error_invalid_card_data
            is ProcessingErrorEvent.INVALID_APPLICATION_INDEX -> R.string.error_invalid_card_data
            is ProcessingErrorEvent.ONLINE_PROCESSING_ERROR -> R.string.error_communication_interrupted
            is ProcessingErrorEvent.EMV_PROCESSING_ERROR -> R.string.error_chip_required
            is ProcessingErrorEvent.EMV_CARD_CONNECTION_ERROR -> R.string.error_emv_card_connection_error
            is ProcessingErrorEvent.EMV_NO_APPLICATION -> R.string.error_emv_no_application
            is ProcessingErrorEvent.EMV_CAPK_ERROR -> R.string.error_emv_capk_error
            is ProcessingErrorEvent.EMV_TLV_ERROR -> R.string.error_emv_tlv_error
            is ProcessingErrorEvent.EMV_AID_ERROR -> R.string.error_emv_aid_error
            is ProcessingErrorEvent.PIN_ENTRY_ERROR -> R.string.error_pin_entry_error
            is ProcessingErrorEvent.PIN_KEY_ERROR -> R.string.error_pin_key_error
            is ProcessingErrorEvent.PIN_NO_INPUT -> R.string.error_pin_no_input
            is ProcessingErrorEvent.PIN_INITIALIZATION_ERROR -> R.string.error_pin_initialization_error
            is ProcessingErrorEvent.PIN_ENCRYPTION_ERROR -> R.string.error_pin_encryption_error
            is ProcessingErrorEvent.PIN_KEY_NOT_FOUND -> R.string.error_pin_key_not_found
            is ProcessingErrorEvent.NFC_NOT_SUPPORTED -> R.string.error_feature_unavailable
            is ProcessingErrorEvent.NFC_OPERATION_ABORTED -> R.string.error_operation_cancelled_retry
            is ProcessingErrorEvent.NFC_WRONG_CARD_TYPE -> R.string.error_invalid_card_use_another
            is ProcessingErrorEvent.NFC_INVALID_KEY -> R.string.error_nfc_invalid_key
            is ProcessingErrorEvent.NFC_NOT_AUTHENTICATED -> R.string.error_authentication_error
            is ProcessingErrorEvent.INVALID_SECTOR_NUMBER -> R.string.error_invalid_sector_number
            is ProcessingErrorEvent.INVALID_BLOCK_NUMBER -> R.string.error_invalid_block_number
            is ProcessingErrorEvent.INVALID_BLOCK_FORMAT -> R.string.error_invalid_block_format
            is ProcessingErrorEvent.QRCODE_GENERATION_ERROR -> R.string.error_qrcode_generation_error
            is ProcessingErrorEvent.QRCODE_EXPIRED -> R.string.error_qrcode_expired
            is ProcessingErrorEvent.TRANSACTION_FALLBACK -> R.string.error_transaction_fallback
            is ProcessingErrorEvent.INVALID_CARD_MODE -> R.string.error_invalid_mode
            is ProcessingErrorEvent.TOO_MANY_CARDS -> R.string.error_too_many_cards
            is ProcessingErrorEvent.DEVICE_MISCONFIGURED -> R.string.error_device_misconfigured
            is ProcessingErrorEvent.ACTIVATION_ERROR -> R.string.error_activation_error
            is ProcessingErrorEvent.SDK_VERSION_OUTDATED -> R.string.error_update_app
            is ProcessingErrorEvent.APP_NAME_NOT_SET -> R.string.error_application_name_required
            is ProcessingErrorEvent.NO_ACTIVE_APPLICATION -> R.string.error_no_active_application
            is ProcessingErrorEvent.MULTIPLE_PROVIDER_INSTANCES -> R.string.error_multiple_provider_instances
            is ProcessingErrorEvent.UNKNOWN_USER_TYPE -> R.string.error_unknown_user_type
            is ProcessingErrorEvent.TRANSACTION_OBJECT_NULL -> R.string.error_null_transaction_result
            is ProcessingErrorEvent.EMAIL_ERROR -> R.string.error_email_error
            is ProcessingErrorEvent.EMAIL_CLIENT_ERROR -> R.string.error_email_client_error
            is ProcessingErrorEvent.EMAIL_EMPTY -> R.string.error_email_empty
            is ProcessingErrorEvent.EMAIL_RECIPIENT_EMPTY -> R.string.error_email_recipient_empty
            is ProcessingErrorEvent.DATA_CONSTRAINT_ERROR -> R.string.error_data_constraint_error
            is ProcessingErrorEvent.DATA_INTEGRATION_ERROR -> R.string.error_data_integration_error
            is ProcessingErrorEvent.SWITCH_INTERFACE_ERROR -> R.string.error_switch_interface_error
            is ProcessingErrorEvent.SWIPE_INCORRECT -> R.string.error_card_error_poorly_inserted
            is ProcessingErrorEvent.NULL_RESPONSE -> R.string.error_null_response
            is ProcessingErrorEvent.ERROR_RESPONSE -> R.string.error_error_response
            is ProcessingErrorEvent.CARD_REMOVED_BY_USER -> R.string.error_card_removed_by_user
            is ProcessingErrorEvent.CHIP_CARD_READ_ERROR -> R.string.error_chip_card_read_error
            is ProcessingErrorEvent.CARD_GENERIC_ERROR -> R.string.error_card_generic_error
            is ProcessingErrorEvent.DEVICE_NOT_COMPATIBLE -> R.string.error_device_not_compatible
            is ProcessingErrorEvent.MAG_STRIPE_CHIP_DETECTED -> R.string.error_use_chip_for_transaction
            is ProcessingErrorEvent.INVALID_ACQUIRER_ACTIVATION_CODE -> R.string.error_invalid_reader_or_activation_code
            is ProcessingErrorEvent.INVALID_STONE_CODE -> R.string.error_invalid_reader_or_activation_code
            is ProcessingErrorEvent.USER_MODEL_NOT_FOUND -> R.string.error_user_model_not_found
            is ProcessingErrorEvent.INVALID_OR_UNKNOWN_STONE_CODE -> R.string.error_invalid_or_unknown_stone_code
            is ProcessingErrorEvent.PRINTER_INITIALIZATION_ERROR -> R.string.error_printer_initialization_error
            is ProcessingErrorEvent.PRINTER_UNSUPPORTED_FORMAT -> R.string.error_printer_unsupported_format
            is ProcessingErrorEvent.PRINTER_INVALID_DATA -> R.string.error_printer_invalid_data
            is ProcessingErrorEvent.NO_PRINT_SUPPORT -> R.string.error_no_print_support
            is ProcessingErrorEvent.INTERNAL_SYSTEM_ERROR -> R.string.error_unexpected_error
            is ProcessingErrorEvent.TABLES_NOT_FOUND -> R.string.error_tables_not_found
            is ProcessingErrorEvent.NEED_LOAD_TABLES -> R.string.error_need_load_tables
            is ProcessingErrorEvent.REVERSAL_PENDING -> R.string.error_reversal_pending
            is ProcessingErrorEvent.TRANSACTION_PENDING -> R.string.error_transaction_pending
            is ProcessingErrorEvent.CANCELLED_AWAITING_REVERSAL -> R.string.error_cancelled_awaiting_reversal
            is ProcessingErrorEvent.FRAUD_SUSPICION -> R.string.error_fraud_suspicion
            is ProcessingErrorEvent.CHECK_CARD_DETAILS -> R.string.error_check_card_details
            is ProcessingErrorEvent.USE_CREDIT_METHOD -> R.string.error_use_credit_method
            is ProcessingErrorEvent.USE_DEBIT_METHOD -> R.string.error_use_debit_method
            is ProcessingErrorEvent.CHECK_SPECIAL_CONDITIONS -> R.string.error_check_special_conditions
            is ProcessingErrorEvent.APPROVE_AFTER_IDENTITY_VERIFICATION -> R.string.error_approve_after_identity_verification
            is ProcessingErrorEvent.UNACCEPTABLE_FEE -> R.string.error_unacceptable_fee
            is ProcessingErrorEvent.CARD_WITH_RESTRICTION -> R.string.error_card_with_restriction
            is ProcessingErrorEvent.EXCEEDED_PASSWORD_ATTEMPTS -> R.string.error_exceeded_password_attempts
            is ProcessingErrorEvent.LOST_CARD -> R.string.error_lost_card
            is ProcessingErrorEvent.STOLEN_CARD -> R.string.error_stolen_card
            is ProcessingErrorEvent.EXCEEDED_HEALTH_VALUE_LIMIT -> R.string.error_exceeded_health_value_limit
            is ProcessingErrorEvent.EXCEEDED_WITHDRAWAL_QUANTITY_LIMIT -> R.string.error_exceeded_withdrawal_quantity_limit
            is ProcessingErrorEvent.CUTOVER_IN_PROCESS -> R.string.error_cutover_in_process
            is ProcessingErrorEvent.VIOLATION_OF_LAW -> R.string.error_violation_of_law
            is ProcessingErrorEvent.RECONCILIATION_ERROR -> R.string.error_reconciliation_error
            is ProcessingErrorEvent.POOR_STATUS_DESTINATION -> R.string.error_poor_status_destination
            is ProcessingErrorEvent.POOR_STATUS_ORIGIN -> R.string.error_poor_status_origin
            is ProcessingErrorEvent.REJECTED_KEY_VERIFICATION_FAILED -> R.string.error_rejected_key_verification_failed
            is ProcessingErrorEvent.ISSUER_UNAVAILABLE -> R.string.error_issuer_unavailable
            is ProcessingErrorEvent.INVALID_LIFE_CYCLE -> R.string.error_invalid_life_cycle
            is ProcessingErrorEvent.UNBLOCK_THE_CARD -> R.string.error_unblock_the_card
            else -> R.string.event_generic_error
        }
    }
}
